### ISSUE TITLE
YAML file instead of txt files in folders

### ISSUE THREAD

**Issue by isuruf** [conda-forge/admin-requests#879]
Now that we have lots of different folders, maybe it's time to use a YAML file instead of a `.txt` file with a list.

For eg:
```yaml
packages:
  - linux-64/win-64/cf-autotick-bot-test-package-0.4-py38_0.tar.bz2
  - win-64/cf-autotick-bot-test-package-0.4-py27_0.tar.bz2
action: broken/not_broken
```

```yaml
feedstocks:
  - cf-autotick-bot-test-package
action: archive/unarchive
```

```yaml
feedstocks:
  - cf-autotick-bot-test-package
action: grant_access
resource:
  - gpu-runner
  - gpu-runner-pr
  - cpu-runner
```

```yaml
feedstocks:
  - cf-autotick-bot-test-package
action: token_reset
ci:
  - github_actions
  - travis
```

cc @beckermr, @jaimergp
